site_name: docs-test
site_url: https://mohammad-h93.github.io/docs-test/

nav:
  - Home: index.md
  - Page Two: page-2.md

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
